name: release
on:
  push:
    # 监听 master 分支的 push 事件
    branches:
      - master
# 赋予 release-please-action 权限
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  # 创建发布 PR 或标签
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: 创建发布 PR
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

  # 发布到 npm
  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: 设置 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true

      - name: 构建输出
        run: pnpm build

      - name: 发布到 npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
